//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Creature.proto
namespace Creature
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Creature")]
  public partial class Creature : global::ProtoBuf.IExtensible
  {
    public Creature() {}
    
    private readonly global::System.Collections.Generic.List<Creature.Item> _items = new global::System.Collections.Generic.List<Creature.Item>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Creature.Item> items
    {
      get { return _items; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Item")]
  public partial class Item : global::ProtoBuf.IExtensible
  {
    public Item() {}
    
    private int _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private string _Res;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Res", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Res
    {
      get { return _Res; }
      set { _Res = value; }
    }
    private string _Colour;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Colour", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Colour
    {
      get { return _Colour; }
      set { _Colour = value; }
    }
    private string _Size;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Size", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Size
    {
      get { return _Size; }
      set { _Size = value; }
    }
    private string _Play;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Play", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Play
    {
      get { return _Play; }
      set { _Play = value; }
    }
    private int _Ps;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"Ps", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Ps
    {
      get { return _Ps; }
      set { _Ps = value; }
    }
    private int _Ms;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"Ms", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Ms
    {
      get { return _Ms; }
      set { _Ms = value; }
    }
    private int _Ds;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"Ds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Ds
    {
      get { return _Ds; }
      set { _Ds = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}