//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LoginMessage.proto
namespace LoginMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CL_Login_Register")]
  public partial class CL_Login_Register : global::ProtoBuf.IExtensible
  {
    public CL_Login_Register() {}
    
    private string _UserName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string UserName
    {
      get { return _UserName; }
      set { _UserName = value; }
    }
    private string _Password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private string _RegisterOS;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"RegisterOS", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RegisterOS
    {
      get { return _RegisterOS; }
      set { _RegisterOS = value; }
    }
    private string _RegisterHW;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"RegisterHW", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RegisterHW
    {
      get { return _RegisterHW; }
      set { _RegisterHW = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LC_Login_Register")]
  public partial class LC_Login_Register : global::ProtoBuf.IExtensible
  {
    public LC_Login_Register() {}
    
    private uint _Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CL_Login_LoginUser")]
  public partial class CL_Login_LoginUser : global::ProtoBuf.IExtensible
  {
    public CL_Login_LoginUser() {}
    
    private string _UserName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string UserName
    {
      get { return _UserName; }
      set { _UserName = value; }
    }
    private string _Password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private string _LoginOS;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"LoginOS", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string LoginOS
    {
      get { return _LoginOS; }
      set { _LoginOS = value; }
    }
    private string _LoginHW;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"LoginHW", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string LoginHW
    {
      get { return _LoginHW; }
      set { _LoginHW = value; }
    }
    private uint _LoginID;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"LoginID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint LoginID
    {
      get { return _LoginID; }
      set { _LoginID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LC_Login_LoginUser")]
  public partial class LC_Login_LoginUser : global::ProtoBuf.IExtensible
  {
    public LC_Login_LoginUser() {}
    
    private uint _Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LC_Login_ActorList")]
  public partial class LC_Login_ActorList : global::ProtoBuf.IExtensible
  {
    public LC_Login_ActorList() {}
    
    private readonly global::System.Collections.Generic.List<LC_Login_ActorList.ActorInfo> _ActorList = new global::System.Collections.Generic.List<LC_Login_ActorList.ActorInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"ActorList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<LC_Login_ActorList.ActorInfo> ActorList
    {
      get { return _ActorList; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActorInfo")]
  public partial class ActorInfo : global::ProtoBuf.IExtensible
  {
    public ActorInfo() {}
    
    private uint _ActorID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ActorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ActorID
    {
      get { return _ActorID; }
      set { _ActorID = value; }
    }
    private string _ActorName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ActorName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ActorName
    {
      get { return _ActorName; }
      set { _ActorName = value; }
    }
    private uint _Level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private uint _Vocation;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Vocation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Vocation
    {
      get { return _Vocation; }
      set { _Vocation = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CL_Login_CreateActor")]
  public partial class CL_Login_CreateActor : global::ProtoBuf.IExtensible
  {
    public CL_Login_CreateActor() {}
    
    private string _ActorName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ActorName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ActorName
    {
      get { return _ActorName; }
      set { _ActorName = value; }
    }
    private string _CreateOS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"CreateOS", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string CreateOS
    {
      get { return _CreateOS; }
      set { _CreateOS = value; }
    }
    private string _CreateHW;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"CreateHW", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string CreateHW
    {
      get { return _CreateHW; }
      set { _CreateHW = value; }
    }
    private uint _Vocation;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Vocation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Vocation
    {
      get { return _Vocation; }
      set { _Vocation = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LC_Login_CreateActor")]
  public partial class LC_Login_CreateActor : global::ProtoBuf.IExtensible
  {
    public LC_Login_CreateActor() {}
    
    private uint _Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private LC_Login_CreateActor.ActorInfo _NewActor = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"NewActor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public LC_Login_CreateActor.ActorInfo NewActor
    {
      get { return _NewActor; }
      set { _NewActor = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActorInfo")]
  public partial class ActorInfo : global::ProtoBuf.IExtensible
  {
    public ActorInfo() {}
    
    private uint _ActorID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ActorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ActorID
    {
      get { return _ActorID; }
      set { _ActorID = value; }
    }
    private string _ActorName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ActorName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ActorName
    {
      get { return _ActorName; }
      set { _ActorName = value; }
    }
    private uint _Level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private uint _Vocation;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Vocation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Vocation
    {
      get { return _Vocation; }
      set { _Vocation = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CL_Login_DeleteActor")]
  public partial class CL_Login_DeleteActor : global::ProtoBuf.IExtensible
  {
    public CL_Login_DeleteActor() {}
    
    private uint _ActorID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ActorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ActorID
    {
      get { return _ActorID; }
      set { _ActorID = value; }
    }
    private string _ActorName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ActorName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ActorName
    {
      get { return _ActorName; }
      set { _ActorName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LC_Login_DeleteActor")]
  public partial class LC_Login_DeleteActor : global::ProtoBuf.IExtensible
  {
    public LC_Login_DeleteActor() {}
    
    private uint _Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private uint _ActorID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ActorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ActorID
    {
      get { return _ActorID; }
      set { _ActorID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CL_Login_SeleteActor")]
  public partial class CL_Login_SeleteActor : global::ProtoBuf.IExtensible
  {
    public CL_Login_SeleteActor() {}
    
    private uint _ActorID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ActorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ActorID
    {
      get { return _ActorID; }
      set { _ActorID = value; }
    }
    private string _ActorName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ActorName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ActorName
    {
      get { return _ActorName; }
      set { _ActorName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LC_Login_SeleteActor")]
  public partial class LC_Login_SeleteActor : global::ProtoBuf.IExtensible
  {
    public LC_Login_SeleteActor() {}
    
    private uint _Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LS_Login_SeleteActor")]
  public partial class LS_Login_SeleteActor : global::ProtoBuf.IExtensible
  {
    public LS_Login_SeleteActor() {}
    
    private uint _ClientID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ClientID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ClientID
    {
      get { return _ClientID; }
      set { _ClientID = value; }
    }
    private uint _UserID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"UserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint UserID
    {
      get { return _UserID; }
      set { _UserID = value; }
    }
    private uint _ActorID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ActorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ActorID
    {
      get { return _ActorID; }
      set { _ActorID = value; }
    }
    private string _UserName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"UserName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string UserName
    {
      get { return _UserName; }
      set { _UserName = value; }
    }
    private string _ActorName;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"ActorName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ActorName
    {
      get { return _ActorName; }
      set { _ActorName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MSG_LOGIN_ACTIONID")]
    public enum MSG_LOGIN_ACTIONID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIN_NONE", Value=0)]
      MSG_LOGIN_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIN_REGISTER", Value=1)]
      MSG_LOGIN_REGISTER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIN_LOGINUSER", Value=2)]
      MSG_LOGIN_LOGINUSER = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIN_ACTORLIST", Value=3)]
      MSG_LOGIN_ACTORLIST = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIN_CREATEACTOR", Value=4)]
      MSG_LOGIN_CREATEACTOR = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIN_DELETEACTOR", Value=5)]
      MSG_LOGIN_DELETEACTOR = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIN_SELETEACTOR", Value=6)]
      MSG_LOGIN_SELETEACTOR = 6
    }
  
}