//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message.proto
namespace message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegisterUserRequest")]
  public partial class RegisterUserRequest : global::ProtoBuf.IExtensible
  {
    public RegisterUserRequest() {}
    
    private string _UserName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string UserName
    {
      get { return _UserName; }
      set { _UserName = value; }
    }
    private string _Password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private string _RegisterOS;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"RegisterOS", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RegisterOS
    {
      get { return _RegisterOS; }
      set { _RegisterOS = value; }
    }
    private string _RegisterHW;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"RegisterHW", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RegisterHW
    {
      get { return _RegisterHW; }
      set { _RegisterHW = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegisterUserReply")]
  public partial class RegisterUserReply : global::ProtoBuf.IExtensible
  {
    public RegisterUserReply() {}
    
    private uint _Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}