# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='animation.proto',
  package='',
  serialized_pb=_b('\n\x0f\x61nimation.proto\"\x9f\x01\n\tanimation\x12\'\n\x05items\x18\x01 \x03(\x0b\x32\x18.animation.animationItem\x1ai\n\ranimationItem\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x0e\n\x06\x63oment\x18\x03 \x02(\t\x12\x0e\n\x06length\x18\x04 \x02(\x02\x12\x10\n\x08keyframe\x18\x05 \x02(\t\x12\x0c\n\x04path\x18\x06 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ANIMATION_ANIMATIONITEM = _descriptor.Descriptor(
  name='animationItem',
  full_name='animation.animationItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='animation.animationItem.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='animation.animationItem.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coment', full_name='animation.animationItem.coment', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='length', full_name='animation.animationItem.length', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='keyframe', full_name='animation.animationItem.keyframe', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path', full_name='animation.animationItem.path', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=179,
)

_ANIMATION = _descriptor.Descriptor(
  name='animation',
  full_name='animation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='animation.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ANIMATION_ANIMATIONITEM, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=179,
)

_ANIMATION_ANIMATIONITEM.containing_type = _ANIMATION
_ANIMATION.fields_by_name['items'].message_type = _ANIMATION_ANIMATIONITEM
DESCRIPTOR.message_types_by_name['animation'] = _ANIMATION

animation = _reflection.GeneratedProtocolMessageType('animation', (_message.Message,), dict(

  animationItem = _reflection.GeneratedProtocolMessageType('animationItem', (_message.Message,), dict(
    DESCRIPTOR = _ANIMATION_ANIMATIONITEM,
    __module__ = 'animation_pb2'
    # @@protoc_insertion_point(class_scope:animation.animationItem)
    ))
  ,
  DESCRIPTOR = _ANIMATION,
  __module__ = 'animation_pb2'
  # @@protoc_insertion_point(class_scope:animation)
  ))
_sym_db.RegisterMessage(animation)
_sym_db.RegisterMessage(animation.animationItem)


# @@protoc_insertion_point(module_scope)
