# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Sound.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Sound.proto',
  package='',
  serialized_pb=_b('\n\x0bSound.proto\"\x86\x01\n\x05Sound\x12\x1f\n\x05items\x18\x01 \x03(\x0b\x32\x10.Sound.SoundItem\x1a\\\n\tSoundItem\x12\x0f\n\x07SoundId\x18\x01 \x02(\x05\x12\x0c\n\x04Loop\x18\x02 \x02(\x05\x12\x10\n\x08\x43oolTime\x18\x03 \x02(\x05\x12\x0c\n\x04\x44\x65sc\x18\x04 \x02(\t\x12\x10\n\x08\x46ilename\x18\x05 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SOUND_SOUNDITEM = _descriptor.Descriptor(
  name='SoundItem',
  full_name='Sound.SoundItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='SoundId', full_name='Sound.SoundItem.SoundId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Loop', full_name='Sound.SoundItem.Loop', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CoolTime', full_name='Sound.SoundItem.CoolTime', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Desc', full_name='Sound.SoundItem.Desc', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Filename', full_name='Sound.SoundItem.Filename', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=150,
)

_SOUND = _descriptor.Descriptor(
  name='Sound',
  full_name='Sound',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='Sound.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SOUND_SOUNDITEM, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=150,
)

_SOUND_SOUNDITEM.containing_type = _SOUND
_SOUND.fields_by_name['items'].message_type = _SOUND_SOUNDITEM
DESCRIPTOR.message_types_by_name['Sound'] = _SOUND

Sound = _reflection.GeneratedProtocolMessageType('Sound', (_message.Message,), dict(

  SoundItem = _reflection.GeneratedProtocolMessageType('SoundItem', (_message.Message,), dict(
    DESCRIPTOR = _SOUND_SOUNDITEM,
    __module__ = 'Sound_pb2'
    # @@protoc_insertion_point(class_scope:Sound.SoundItem)
    ))
  ,
  DESCRIPTOR = _SOUND,
  __module__ = 'Sound_pb2'
  # @@protoc_insertion_point(class_scope:Sound)
  ))
_sym_db.RegisterMessage(Sound)
_sym_db.RegisterMessage(Sound.SoundItem)


# @@protoc_insertion_point(module_scope)
